// Code generated by goyacc -p migo -o parser.y.go migo.y. DO NOT EDIT.

//line migo.y:2
package parser

import __yyfmt__ "fmt"

//line migo.y:2

import (
	"io"

	"github.com/nickng/migo/v3"
)

var prog *migo.Program

//line migo.y:13
type migoSymType struct {
	yys    int
	str    string
	num    int
	prog   *migo.Program
	fun    *migo.Function
	stmt   migo.Statement
	stmts  []migo.Statement
	params []*migo.Parameter
	cases  [][]migo.Statement
}

const tCOMMA = 57346
const tDEF = 57347
const tEQ = 57348
const tLPAREN = 57349
const tRPAREN = 57350
const tCOLON = 57351
const tSEMICOLON = 57352
const tCALL = 57353
const tSPAWN = 57354
const tCASE = 57355
const tCLOSE = 57356
const tELSE = 57357
const tENDIF = 57358
const tENDSELECT = 57359
const tIF = 57360
const tLET = 57361
const tNEWCHAN = 57362
const tSELECT = 57363
const tSEND = 57364
const tRECV = 57365
const tTAU = 57366
const tLETMEM = 57367
const tREAD = 57368
const tWRITE = 57369
const tLETSYNC = 57370
const tMUTEX = 57371
const tLOCK = 57372
const tUNLOCK = 57373
const tRWMUTEX = 57374
const tRLOCK = 57375
const tRUNLOCK = 57376
const tIDENT = 57377
const tDIGITS = 57378

var migoToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tCOMMA",
	"tDEF",
	"tEQ",
	"tLPAREN",
	"tRPAREN",
	"tCOLON",
	"tSEMICOLON",
	"tCALL",
	"tSPAWN",
	"tCASE",
	"tCLOSE",
	"tELSE",
	"tENDIF",
	"tENDSELECT",
	"tIF",
	"tLET",
	"tNEWCHAN",
	"tSELECT",
	"tSEND",
	"tRECV",
	"tTAU",
	"tLETMEM",
	"tREAD",
	"tWRITE",
	"tLETSYNC",
	"tMUTEX",
	"tLOCK",
	"tUNLOCK",
	"tRWMUTEX",
	"tRLOCK",
	"tRUNLOCK",
	"tIDENT",
	"tDIGITS",
}
var migoStatenames = [...]string{}

const migoEofCode = 1
const migoErrCode = 2
const migoInitialStackSize = 16

//line migo.y:94

// Parse is the entry point to the migo type parser
func Parse(r io.Reader) (*migo.Program, error) {
	l := NewLexer(r)
	migoParse(l)
	select {
	case err := <-l.Errors:
		return nil, err
	default:
		return prog, nil
	}
}

//line yacctab:1
var migoExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const migoPrivate = 57344

const migoLast = 126

var migoAct = [...]int{

	47, 16, 23, 24, 7, 22, 86, 79, 76, 25,
	15, 8, 26, 27, 28, 29, 17, 30, 31, 19,
	56, 32, 33, 55, 34, 35, 23, 24, 54, 22,
	65, 53, 52, 25, 15, 51, 26, 27, 28, 29,
	17, 30, 31, 19, 50, 32, 33, 49, 34, 35,
	63, 46, 45, 44, 41, 39, 37, 12, 5, 59,
	68, 87, 60, 27, 28, 29, 73, 71, 72, 75,
	67, 11, 23, 24, 66, 22, 84, 83, 82, 25,
	15, 85, 26, 27, 28, 29, 17, 30, 31, 19,
	64, 32, 33, 80, 34, 35, 74, 70, 69, 61,
	58, 43, 14, 42, 36, 40, 38, 10, 10, 10,
	81, 78, 77, 9, 62, 6, 57, 3, 2, 1,
	4, 48, 13, 21, 20, 18,
}
var migoPact = [...]int{

	112, 112, -1000, 23, -1000, 108, -24, 105, -1000, 62,
	22, 61, -1000, 61, -1000, 21, 96, 20, 95, 19,
	93, 91, 18, 17, 16, -1000, -1000, 12, 9, -1000,
	0, -3, -4, -7, -12, -15, -1000, 110, -1000, 90,
	-1000, 30, -1000, -1000, 89, 107, 43, 15, 57, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 40, -1000, 88,
	87, -1000, -24, -24, -1000, -1000, 86, 41, -27, -1000,
	-1000, 104, 103, -9, -1000, 83, 106, 68, 67, 66,
	-1000, -30, -1000, -1000, -1000, 61, 51, -1000,
}
var migoPgo = [...]int{

	0, 1, 125, 124, 123, 90, 118, 4, 0, 122,
	121, 119,
}
var migoR1 = [...]int{

	0, 11, 11, 6, 7, 7, 7, 9, 9, 8,
	8, 1, 1, 1, 2, 2, 3, 3, 4, 4,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 10, 10,
}
var migoR2 = [...]int{

	0, 1, 2, 7, 0, 1, 3, 1, 2, 0,
	2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
	8, 2, 3, 2, 4, 4, 2, 2, 3, 6,
	6, 6, 4, 0, 5,
}
var migoChk = [...]int{

	-1000, -11, -6, 5, -6, 35, 7, -7, 35, 8,
	4, 9, 35, -9, -5, 19, -1, 25, -2, 28,
	-3, -4, 14, 11, 12, 18, 21, 22, 23, 24,
	26, 27, 30, 31, 33, 34, -5, 35, 10, 35,
	10, 35, 10, 10, 35, 35, 35, -8, -10, 35,
	35, 35, 35, 35, 35, 35, 35, 6, 10, 29,
	32, 10, 7, 7, -5, 15, 17, 13, 20, 10,
	10, -7, -7, -8, 10, -1, 35, 8, 8, 16,
	10, 4, 10, 10, 10, -8, 36, 10,
}
var migoDef = [...]int{

	0, -2, 1, 0, 2, 0, 4, 0, 5, 0,
	0, 0, 6, 3, 7, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 9, 33, 0, 0, 13,
	0, 0, 0, 0, 0, 0, 8, 0, 21, 0,
	23, 0, 26, 27, 0, 0, 0, 0, 0, 11,
	12, 14, 15, 16, 17, 18, 19, 0, 22, 0,
	0, 28, 4, 4, 10, 9, 0, 0, 0, 24,
	25, 0, 0, 0, 32, 0, 0, 0, 0, 0,
	9, 0, 29, 30, 31, 34, 0, 20,
}
var migoTok1 = [...]int{

	1,
}
var migoTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36,
}
var migoTok3 = [...]int{
	0,
}

var migoErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	migoDebug        = 0
	migoErrorVerbose = false
)

type migoLexer interface {
	Lex(lval *migoSymType) int
	Error(s string)
}

type migoParser interface {
	Parse(migoLexer) int
	Lookahead() int
}

type migoParserImpl struct {
	lval  migoSymType
	stack [migoInitialStackSize]migoSymType
	char  int
}

func (p *migoParserImpl) Lookahead() int {
	return p.char
}

func migoNewParser() migoParser {
	return &migoParserImpl{}
}

const migoFlag = -1000

func migoTokname(c int) string {
	if c >= 1 && c-1 < len(migoToknames) {
		if migoToknames[c-1] != "" {
			return migoToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func migoStatname(s int) string {
	if s >= 0 && s < len(migoStatenames) {
		if migoStatenames[s] != "" {
			return migoStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func migoErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !migoErrorVerbose {
		return "syntax error"
	}

	for _, e := range migoErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + migoTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := migoPact[state]
	for tok := TOKSTART; tok-1 < len(migoToknames); tok++ {
		if n := base + tok; n >= 0 && n < migoLast && migoChk[migoAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if migoDef[state] == -2 {
		i := 0
		for migoExca[i] != -1 || migoExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; migoExca[i] >= 0; i += 2 {
			tok := migoExca[i]
			if tok < TOKSTART || migoExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if migoExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += migoTokname(tok)
	}
	return res
}

func migolex1(lex migoLexer, lval *migoSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = migoTok1[0]
		goto out
	}
	if char < len(migoTok1) {
		token = migoTok1[char]
		goto out
	}
	if char >= migoPrivate {
		if char < migoPrivate+len(migoTok2) {
			token = migoTok2[char-migoPrivate]
			goto out
		}
	}
	for i := 0; i < len(migoTok3); i += 2 {
		token = migoTok3[i+0]
		if token == char {
			token = migoTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = migoTok2[1] /* unknown char */
	}
	if migoDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", migoTokname(token), uint(char))
	}
	return char, token
}

func migoParse(migolex migoLexer) int {
	return migoNewParser().Parse(migolex)
}

func (migorcvr *migoParserImpl) Parse(migolex migoLexer) int {
	var migon int
	var migoVAL migoSymType
	var migoDollar []migoSymType
	_ = migoDollar // silence set and not used
	migoS := migorcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	migostate := 0
	migorcvr.char = -1
	migotoken := -1 // migorcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		migostate = -1
		migorcvr.char = -1
		migotoken = -1
	}()
	migop := -1
	goto migostack

ret0:
	return 0

ret1:
	return 1

migostack:
	/* put a state and value onto the stack */
	if migoDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", migoTokname(migotoken), migoStatname(migostate))
	}

	migop++
	if migop >= len(migoS) {
		nyys := make([]migoSymType, len(migoS)*2)
		copy(nyys, migoS)
		migoS = nyys
	}
	migoS[migop] = migoVAL
	migoS[migop].yys = migostate

migonewstate:
	migon = migoPact[migostate]
	if migon <= migoFlag {
		goto migodefault /* simple state */
	}
	if migorcvr.char < 0 {
		migorcvr.char, migotoken = migolex1(migolex, &migorcvr.lval)
	}
	migon += migotoken
	if migon < 0 || migon >= migoLast {
		goto migodefault
	}
	migon = migoAct[migon]
	if migoChk[migon] == migotoken { /* valid shift */
		migorcvr.char = -1
		migotoken = -1
		migoVAL = migorcvr.lval
		migostate = migon
		if Errflag > 0 {
			Errflag--
		}
		goto migostack
	}

migodefault:
	/* default state action */
	migon = migoDef[migostate]
	if migon == -2 {
		if migorcvr.char < 0 {
			migorcvr.char, migotoken = migolex1(migolex, &migorcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if migoExca[xi+0] == -1 && migoExca[xi+1] == migostate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			migon = migoExca[xi+0]
			if migon < 0 || migon == migotoken {
				break
			}
		}
		migon = migoExca[xi+1]
		if migon < 0 {
			goto ret0
		}
	}
	if migon == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			migolex.Error(migoErrorMessage(migostate, migotoken))
			Nerrs++
			if migoDebug >= 1 {
				__yyfmt__.Printf("%s", migoStatname(migostate))
				__yyfmt__.Printf(" saw %s\n", migoTokname(migotoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for migop >= 0 {
				migon = migoPact[migoS[migop].yys] + migoErrCode
				if migon >= 0 && migon < migoLast {
					migostate = migoAct[migon] /* simulate a shift of "error" */
					if migoChk[migostate] == migoErrCode {
						goto migostack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if migoDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", migoS[migop].yys)
				}
				migop--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if migoDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", migoTokname(migotoken))
			}
			if migotoken == migoEofCode {
				goto ret1
			}
			migorcvr.char = -1
			migotoken = -1
			goto migonewstate /* try again in the same state */
		}
	}

	/* reduction by production migon */
	if migoDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", migon, migoStatname(migostate))
	}

	migont := migon
	migopt := migop
	_ = migopt // guard against "declared and not used"

	migop -= migoR2[migon]
	// migop is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if migop+1 >= len(migoS) {
		nyys := make([]migoSymType, len(migoS)*2)
		copy(nyys, migoS)
		migoS = nyys
	}
	migoVAL = migoS[migop+1]

	/* consult goto table to find next state */
	migon = migoR1[migon]
	migog := migoPgo[migon]
	migoj := migog + migoS[migop].yys + 1

	if migoj >= migoLast {
		migostate = migoAct[migog]
	} else {
		migostate = migoAct[migoj]
		if migoChk[migostate] != -migon {
			migostate = migoAct[migog]
		}
	}
	// dummy call; replaced with literal code
	switch migont {

	case 1:
		migoDollar = migoS[migopt-1 : migopt+1]
//line migo.y:38
		{
			prog = migo.NewProgram()
			migoVAL.prog = prog
			prog.AddFunction(migoDollar[1].fun)
		}
	case 2:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:39
		{
			migoDollar[1].prog.AddFunction(migoDollar[2].fun)
		}
	case 3:
		migoDollar = migoS[migopt-7 : migopt+1]
//line migo.y:42
		{
			migoVAL.fun = migo.NewFunction(migoDollar[2].str)
			migoVAL.fun.AddParams(migoDollar[4].params...)
			migoVAL.fun.AddStmts(migoDollar[7].stmts...)
		}
	case 4:
		migoDollar = migoS[migopt-0 : migopt+1]
//line migo.y:45
		{
			migoVAL.params = params()
		}
	case 5:
		migoDollar = migoS[migopt-1 : migopt+1]
//line migo.y:46
		{
			migoVAL.params = params(plainParam(migoDollar[1].str))
		}
	case 6:
		migoDollar = migoS[migopt-3 : migopt+1]
//line migo.y:47
		{
			migoVAL.params = append(migoDollar[1].params, plainParam(migoDollar[3].str))
		}
	case 7:
		migoDollar = migoS[migopt-1 : migopt+1]
//line migo.y:50
		{
			migoVAL.stmts = stmts(migoDollar[1].stmt)
		}
	case 8:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:51
		{
			migoVAL.stmts = append(migoDollar[1].stmts, migoDollar[2].stmt)
		}
	case 9:
		migoDollar = migoS[migopt-0 : migopt+1]
//line migo.y:54
		{
			migoVAL.stmts = stmts()
		}
	case 10:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:55
		{
			migoVAL.stmts = append(migoDollar[1].stmts, migoDollar[2].stmt)
		}
	case 11:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:58
		{
			migoVAL.stmt = sendStmt(migoDollar[2].str)
		}
	case 12:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:59
		{
			migoVAL.stmt = recvStmt(migoDollar[2].str)
		}
	case 13:
		migoDollar = migoS[migopt-1 : migopt+1]
//line migo.y:60
		{
			migoVAL.stmt = tauStmt()
		}
	case 14:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:63
		{
			migoVAL.stmt = readStmt(migoDollar[2].str)
		}
	case 15:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:64
		{
			migoVAL.stmt = writeStmt(migoDollar[2].str)
		}
	case 16:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:67
		{
			migoVAL.stmt = lockStmt(migoDollar[2].str)
		}
	case 17:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:68
		{
			migoVAL.stmt = unlockStmt(migoDollar[2].str)
		}
	case 18:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:71
		{
			migoVAL.stmt = rlockStmt(migoDollar[2].str)
		}
	case 19:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:72
		{
			migoVAL.stmt = runlockStmt(migoDollar[2].str)
		}
	case 20:
		migoDollar = migoS[migopt-8 : migopt+1]
//line migo.y:75
		{
			migoVAL.stmt = newchanStmt(migoDollar[2].str, migoDollar[5].str, migoDollar[7].num)
		}
	case 21:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:76
		{
			migoVAL.stmt = migoDollar[1].stmt
		}
	case 22:
		migoDollar = migoS[migopt-3 : migopt+1]
//line migo.y:77
		{
			migoVAL.stmt = newmemStmt(migoDollar[2].str)
		}
	case 23:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:78
		{
			migoVAL.stmt = migoDollar[1].stmt
		}
	case 24:
		migoDollar = migoS[migopt-4 : migopt+1]
//line migo.y:79
		{
			migoVAL.stmt = newMutex(migoDollar[2].str)
		}
	case 25:
		migoDollar = migoS[migopt-4 : migopt+1]
//line migo.y:80
		{
			migoVAL.stmt = newRWMutex(migoDollar[2].str)
		}
	case 26:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:81
		{
			migoVAL.stmt = migoDollar[1].stmt
		}
	case 27:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:82
		{
			migoVAL.stmt = migoDollar[1].stmt
		}
	case 28:
		migoDollar = migoS[migopt-3 : migopt+1]
//line migo.y:83
		{
			migoVAL.stmt = closeStmt(migoDollar[2].str)
		}
	case 29:
		migoDollar = migoS[migopt-6 : migopt+1]
//line migo.y:84
		{
			migoVAL.stmt = callStmt(migoDollar[2].str, migoDollar[4].params)
		}
	case 30:
		migoDollar = migoS[migopt-6 : migopt+1]
//line migo.y:85
		{
			migoVAL.stmt = spawnStmt(migoDollar[2].str, migoDollar[4].params)
		}
	case 31:
		migoDollar = migoS[migopt-6 : migopt+1]
//line migo.y:86
		{
			migoVAL.stmt = ifStmt(migoDollar[2].stmts, migoDollar[4].stmts)
		}
	case 32:
		migoDollar = migoS[migopt-4 : migopt+1]
//line migo.y:87
		{
			migoVAL.stmt = selectStmt(migoDollar[2].cases)
		}
	case 33:
		migoDollar = migoS[migopt-0 : migopt+1]
//line migo.y:90
		{
			migoVAL.cases = cases()
		}
	case 34:
		migoDollar = migoS[migopt-5 : migopt+1]
//line migo.y:91
		{
			migoVAL.cases = append(migoDollar[1].cases, append(stmts(migoDollar[3].stmt), migoDollar[5].stmts...))
		}
	}
	goto migostack /* stack new state and value */
}
