// Code generated by goyacc -p migo -o parser.y.go migo.y. DO NOT EDIT.

//line migo.y:2
package parser

import __yyfmt__ "fmt"

//line migo.y:2

import (
	"io"

	"github.com/nickng/migo/v3"
)

var prog *migo.Program

//line migo.y:13
type migoSymType struct {
	yys    int
	str    string
	num    int
	prog   *migo.Program
	fun    *migo.Function
	stmt   migo.Statement
	stmts  []migo.Statement
	params []*migo.Parameter
	cases  [][]migo.Statement
}

const tCOMMA = 57346
const tDEF = 57347
const tEQ = 57348
const tLPAREN = 57349
const tRPAREN = 57350
const tCOLON = 57351
const tSEMICOLON = 57352
const tCALL = 57353
const tSPAWN = 57354
const tCASE = 57355
const tCLOSE = 57356
const tELSE = 57357
const tENDIF = 57358
const tENDSELECT = 57359
const tIF = 57360
const tLET = 57361
const tNEWCHAN = 57362
const tSELECT = 57363
const tSEND = 57364
const tRECV = 57365
const tTAU = 57366
const tLETMEM = 57367
const tREAD = 57368
const tWRITE = 57369
const tLETSYNC = 57370
const tMUTEX = 57371
const tLOCK = 57372
const tUNLOCK = 57373
const tIDENT = 57374
const tDIGITS = 57375

var migoToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tCOMMA",
	"tDEF",
	"tEQ",
	"tLPAREN",
	"tRPAREN",
	"tCOLON",
	"tSEMICOLON",
	"tCALL",
	"tSPAWN",
	"tCASE",
	"tCLOSE",
	"tELSE",
	"tENDIF",
	"tENDSELECT",
	"tIF",
	"tLET",
	"tNEWCHAN",
	"tSELECT",
	"tSEND",
	"tRECV",
	"tTAU",
	"tLETMEM",
	"tREAD",
	"tWRITE",
	"tLETSYNC",
	"tMUTEX",
	"tLOCK",
	"tUNLOCK",
	"tIDENT",
	"tDIGITS",
}
var migoStatenames = [...]string{}

const migoEofCode = 1
const migoErrCode = 2
const migoInitialStackSize = 16

//line migo.y:88

// Parse is the entry point to the migo type parser
func Parse(r io.Reader) (*migo.Program, error) {
	l := NewLexer(r)
	migoParse(l)
	select {
	case err := <-l.Errors:
		return nil, err
	default:
		return prog, nil
	}
}

//line yacctab:1
var migoExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const migoPrivate = 57344

const migoLast = 114

var migoAct = [...]int{

	43, 16, 22, 23, 7, 21, 78, 71, 68, 24,
	15, 8, 25, 26, 27, 28, 17, 29, 30, 19,
	50, 31, 32, 22, 23, 49, 21, 58, 48, 47,
	24, 15, 46, 25, 26, 27, 28, 17, 29, 30,
	19, 45, 31, 32, 79, 42, 41, 40, 38, 36,
	34, 12, 5, 53, 26, 27, 28, 61, 76, 65,
	63, 64, 67, 11, 22, 23, 75, 21, 74, 72,
	66, 24, 15, 77, 25, 26, 27, 28, 17, 29,
	30, 19, 60, 31, 32, 57, 59, 62, 54, 52,
	39, 37, 35, 56, 10, 55, 10, 14, 70, 33,
	69, 10, 6, 73, 51, 9, 3, 2, 1, 4,
	44, 13, 20, 18,
}
var migoPact = [...]int{

	101, 101, -1000, 20, -1000, 95, -21, 97, -1000, 54,
	19, 53, -1000, 53, -1000, 18, 82, 17, 81, 16,
	80, 15, 14, 13, -1000, -1000, 9, 0, -1000, -3,
	-4, -7, -12, -1000, 98, -1000, 79, -1000, 24, -1000,
	78, 88, 86, 12, 69, -1000, -1000, -1000, -1000, -1000,
	-1000, 37, -1000, 77, -1000, -21, -21, -1000, -1000, 60,
	32, -24, -1000, 92, 90, -9, -1000, 59, 99, 58,
	56, 48, -1000, -27, -1000, -1000, -1000, 53, 34, -1000,
}
var migoPgo = [...]int{

	0, 1, 113, 112, 85, 107, 4, 0, 111, 110,
	108,
}
var migoR1 = [...]int{

	0, 10, 10, 5, 6, 6, 6, 8, 8, 7,
	7, 1, 1, 1, 2, 2, 3, 3, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 9,
	9,
}
var migoR2 = [...]int{

	0, 1, 2, 7, 0, 1, 3, 1, 2, 0,
	2, 2, 2, 1, 2, 2, 2, 2, 8, 2,
	3, 2, 4, 2, 3, 6, 6, 6, 4, 0,
	5,
}
var migoChk = [...]int{

	-1000, -10, -5, 5, -5, 32, 7, -6, 32, 8,
	4, 9, 32, -8, -4, 19, -1, 25, -2, 28,
	-3, 14, 11, 12, 18, 21, 22, 23, 24, 26,
	27, 30, 31, -4, 32, 10, 32, 10, 32, 10,
	32, 32, 32, -7, -9, 32, 32, 32, 32, 32,
	32, 6, 10, 29, 10, 7, 7, -4, 15, 17,
	13, 20, 10, -6, -6, -7, 10, -1, 32, 8,
	8, 16, 10, 4, 10, 10, 10, -7, 33, 10,
}
var migoDef = [...]int{

	0, -2, 1, 0, 2, 0, 4, 0, 5, 0,
	0, 0, 6, 3, 7, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 9, 29, 0, 0, 13, 0,
	0, 0, 0, 8, 0, 19, 0, 21, 0, 23,
	0, 0, 0, 0, 0, 11, 12, 14, 15, 16,
	17, 0, 20, 0, 24, 4, 4, 10, 9, 0,
	0, 0, 22, 0, 0, 0, 28, 0, 0, 0,
	0, 0, 9, 0, 25, 26, 27, 30, 0, 18,
}
var migoTok1 = [...]int{

	1,
}
var migoTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33,
}
var migoTok3 = [...]int{
	0,
}

var migoErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	migoDebug        = 0
	migoErrorVerbose = false
)

type migoLexer interface {
	Lex(lval *migoSymType) int
	Error(s string)
}

type migoParser interface {
	Parse(migoLexer) int
	Lookahead() int
}

type migoParserImpl struct {
	lval  migoSymType
	stack [migoInitialStackSize]migoSymType
	char  int
}

func (p *migoParserImpl) Lookahead() int {
	return p.char
}

func migoNewParser() migoParser {
	return &migoParserImpl{}
}

const migoFlag = -1000

func migoTokname(c int) string {
	if c >= 1 && c-1 < len(migoToknames) {
		if migoToknames[c-1] != "" {
			return migoToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func migoStatname(s int) string {
	if s >= 0 && s < len(migoStatenames) {
		if migoStatenames[s] != "" {
			return migoStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func migoErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !migoErrorVerbose {
		return "syntax error"
	}

	for _, e := range migoErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + migoTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := migoPact[state]
	for tok := TOKSTART; tok-1 < len(migoToknames); tok++ {
		if n := base + tok; n >= 0 && n < migoLast && migoChk[migoAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if migoDef[state] == -2 {
		i := 0
		for migoExca[i] != -1 || migoExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; migoExca[i] >= 0; i += 2 {
			tok := migoExca[i]
			if tok < TOKSTART || migoExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if migoExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += migoTokname(tok)
	}
	return res
}

func migolex1(lex migoLexer, lval *migoSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = migoTok1[0]
		goto out
	}
	if char < len(migoTok1) {
		token = migoTok1[char]
		goto out
	}
	if char >= migoPrivate {
		if char < migoPrivate+len(migoTok2) {
			token = migoTok2[char-migoPrivate]
			goto out
		}
	}
	for i := 0; i < len(migoTok3); i += 2 {
		token = migoTok3[i+0]
		if token == char {
			token = migoTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = migoTok2[1] /* unknown char */
	}
	if migoDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", migoTokname(token), uint(char))
	}
	return char, token
}

func migoParse(migolex migoLexer) int {
	return migoNewParser().Parse(migolex)
}

func (migorcvr *migoParserImpl) Parse(migolex migoLexer) int {
	var migon int
	var migoVAL migoSymType
	var migoDollar []migoSymType
	_ = migoDollar // silence set and not used
	migoS := migorcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	migostate := 0
	migorcvr.char = -1
	migotoken := -1 // migorcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		migostate = -1
		migorcvr.char = -1
		migotoken = -1
	}()
	migop := -1
	goto migostack

ret0:
	return 0

ret1:
	return 1

migostack:
	/* put a state and value onto the stack */
	if migoDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", migoTokname(migotoken), migoStatname(migostate))
	}

	migop++
	if migop >= len(migoS) {
		nyys := make([]migoSymType, len(migoS)*2)
		copy(nyys, migoS)
		migoS = nyys
	}
	migoS[migop] = migoVAL
	migoS[migop].yys = migostate

migonewstate:
	migon = migoPact[migostate]
	if migon <= migoFlag {
		goto migodefault /* simple state */
	}
	if migorcvr.char < 0 {
		migorcvr.char, migotoken = migolex1(migolex, &migorcvr.lval)
	}
	migon += migotoken
	if migon < 0 || migon >= migoLast {
		goto migodefault
	}
	migon = migoAct[migon]
	if migoChk[migon] == migotoken { /* valid shift */
		migorcvr.char = -1
		migotoken = -1
		migoVAL = migorcvr.lval
		migostate = migon
		if Errflag > 0 {
			Errflag--
		}
		goto migostack
	}

migodefault:
	/* default state action */
	migon = migoDef[migostate]
	if migon == -2 {
		if migorcvr.char < 0 {
			migorcvr.char, migotoken = migolex1(migolex, &migorcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if migoExca[xi+0] == -1 && migoExca[xi+1] == migostate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			migon = migoExca[xi+0]
			if migon < 0 || migon == migotoken {
				break
			}
		}
		migon = migoExca[xi+1]
		if migon < 0 {
			goto ret0
		}
	}
	if migon == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			migolex.Error(migoErrorMessage(migostate, migotoken))
			Nerrs++
			if migoDebug >= 1 {
				__yyfmt__.Printf("%s", migoStatname(migostate))
				__yyfmt__.Printf(" saw %s\n", migoTokname(migotoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for migop >= 0 {
				migon = migoPact[migoS[migop].yys] + migoErrCode
				if migon >= 0 && migon < migoLast {
					migostate = migoAct[migon] /* simulate a shift of "error" */
					if migoChk[migostate] == migoErrCode {
						goto migostack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if migoDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", migoS[migop].yys)
				}
				migop--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if migoDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", migoTokname(migotoken))
			}
			if migotoken == migoEofCode {
				goto ret1
			}
			migorcvr.char = -1
			migotoken = -1
			goto migonewstate /* try again in the same state */
		}
	}

	/* reduction by production migon */
	if migoDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", migon, migoStatname(migostate))
	}

	migont := migon
	migopt := migop
	_ = migopt // guard against "declared and not used"

	migop -= migoR2[migon]
	// migop is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if migop+1 >= len(migoS) {
		nyys := make([]migoSymType, len(migoS)*2)
		copy(nyys, migoS)
		migoS = nyys
	}
	migoVAL = migoS[migop+1]

	/* consult goto table to find next state */
	migon = migoR1[migon]
	migog := migoPgo[migon]
	migoj := migog + migoS[migop].yys + 1

	if migoj >= migoLast {
		migostate = migoAct[migog]
	} else {
		migostate = migoAct[migoj]
		if migoChk[migostate] != -migon {
			migostate = migoAct[migog]
		}
	}
	// dummy call; replaced with literal code
	switch migont {

	case 1:
		migoDollar = migoS[migopt-1 : migopt+1]
//line migo.y:38
		{
			prog = migo.NewProgram()
			migoVAL.prog = prog
			prog.AddFunction(migoDollar[1].fun)
		}
	case 2:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:39
		{
			migoDollar[1].prog.AddFunction(migoDollar[2].fun)
		}
	case 3:
		migoDollar = migoS[migopt-7 : migopt+1]
//line migo.y:42
		{
			migoVAL.fun = migo.NewFunction(migoDollar[2].str)
			migoVAL.fun.AddParams(migoDollar[4].params...)
			migoVAL.fun.AddStmts(migoDollar[7].stmts...)
		}
	case 4:
		migoDollar = migoS[migopt-0 : migopt+1]
//line migo.y:45
		{
			migoVAL.params = params()
		}
	case 5:
		migoDollar = migoS[migopt-1 : migopt+1]
//line migo.y:46
		{
			migoVAL.params = params(plainParam(migoDollar[1].str))
		}
	case 6:
		migoDollar = migoS[migopt-3 : migopt+1]
//line migo.y:47
		{
			migoVAL.params = append(migoDollar[1].params, plainParam(migoDollar[3].str))
		}
	case 7:
		migoDollar = migoS[migopt-1 : migopt+1]
//line migo.y:50
		{
			migoVAL.stmts = stmts(migoDollar[1].stmt)
		}
	case 8:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:51
		{
			migoVAL.stmts = append(migoDollar[1].stmts, migoDollar[2].stmt)
		}
	case 9:
		migoDollar = migoS[migopt-0 : migopt+1]
//line migo.y:54
		{
			migoVAL.stmts = stmts()
		}
	case 10:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:55
		{
			migoVAL.stmts = append(migoDollar[1].stmts, migoDollar[2].stmt)
		}
	case 11:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:58
		{
			migoVAL.stmt = sendStmt(migoDollar[2].str)
		}
	case 12:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:59
		{
			migoVAL.stmt = recvStmt(migoDollar[2].str)
		}
	case 13:
		migoDollar = migoS[migopt-1 : migopt+1]
//line migo.y:60
		{
			migoVAL.stmt = tauStmt()
		}
	case 14:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:63
		{
			migoVAL.stmt = readStmt(migoDollar[2].str)
		}
	case 15:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:64
		{
			migoVAL.stmt = writeStmt(migoDollar[2].str)
		}
	case 16:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:67
		{
			migoVAL.stmt = lockStmt(migoDollar[2].str)
		}
	case 17:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:68
		{
			migoVAL.stmt = unlockStmt(migoDollar[2].str)
		}
	case 18:
		migoDollar = migoS[migopt-8 : migopt+1]
//line migo.y:71
		{
			migoVAL.stmt = newchanStmt(migoDollar[2].str, migoDollar[5].str, migoDollar[7].num)
		}
	case 19:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:72
		{
			migoVAL.stmt = migoDollar[1].stmt
		}
	case 20:
		migoDollar = migoS[migopt-3 : migopt+1]
//line migo.y:73
		{
			migoVAL.stmt = newmemStmt(migoDollar[2].str)
		}
	case 21:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:74
		{
			migoVAL.stmt = migoDollar[1].stmt
		}
	case 22:
		migoDollar = migoS[migopt-4 : migopt+1]
//line migo.y:75
		{
			migoVAL.stmt = newMutex(migoDollar[2].str)
		}
	case 23:
		migoDollar = migoS[migopt-2 : migopt+1]
//line migo.y:76
		{
			migoVAL.stmt = migoDollar[1].stmt
		}
	case 24:
		migoDollar = migoS[migopt-3 : migopt+1]
//line migo.y:77
		{
			migoVAL.stmt = closeStmt(migoDollar[2].str)
		}
	case 25:
		migoDollar = migoS[migopt-6 : migopt+1]
//line migo.y:78
		{
			migoVAL.stmt = callStmt(migoDollar[2].str, migoDollar[4].params)
		}
	case 26:
		migoDollar = migoS[migopt-6 : migopt+1]
//line migo.y:79
		{
			migoVAL.stmt = spawnStmt(migoDollar[2].str, migoDollar[4].params)
		}
	case 27:
		migoDollar = migoS[migopt-6 : migopt+1]
//line migo.y:80
		{
			migoVAL.stmt = ifStmt(migoDollar[2].stmts, migoDollar[4].stmts)
		}
	case 28:
		migoDollar = migoS[migopt-4 : migopt+1]
//line migo.y:81
		{
			migoVAL.stmt = selectStmt(migoDollar[2].cases)
		}
	case 29:
		migoDollar = migoS[migopt-0 : migopt+1]
//line migo.y:84
		{
			migoVAL.cases = cases()
		}
	case 30:
		migoDollar = migoS[migopt-5 : migopt+1]
//line migo.y:85
		{
			migoVAL.cases = append(migoDollar[1].cases, append(stmts(migoDollar[3].stmt), migoDollar[5].stmts...))
		}
	}
	goto migostack /* stack new state and value */
}
